apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    meta.helm.sh/release-name: terrakube
    meta.helm.sh/release-namespace: terrakube
  creationTimestamp: "2025-07-26T11:14:26Z"
  generation: 6
  labels:
    app.kubernetes.io/instance: terrakube
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: terrakube
    app.kubernetes.io/version: 2.26.3
    helm.sh/chart: terrakube-3.27.10
  name: terrakube-api
  namespace: terrakube
  resourceVersion: "267235"
  uid: bdcc630d-bbad-4e33-aa52-2f4183374e16
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: terrakube-api
      app.kubernetes.io/instance: terrakube
      app.kubernetes.io/name: terrakube
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: d2282e0cc2dcfb0d587ef9df46ca1f5e984f8f3c7c6a05ae62ef8e9da68d529a
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: terrakube-api
        app.kubernetes.io/instance: terrakube
        app.kubernetes.io/name: terrakube
    spec:
      automountServiceAccountToken: true
      containers:
      - envFrom:
        - secretRef:
            name: terrakube-api-secrets
        image: azbuilder/api-server:2.26.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: terrakube-api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /actuator/health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-26T11:29:37Z"
    lastUpdateTime: "2025-07-26T11:29:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-26T11:27:36Z"
    lastUpdateTime: "2025-07-27T07:05:17Z"
    message: ReplicaSet "terrakube-api-bd59f4954" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
